spring.application.name=demo

# Puerto del servidor
server.port=8080

# Conexión a la base de datos MySQL
# Conexión a la base de datos MySQL (Dinámica)
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/appcake?useSSL=false&serverTimezone=UTC}

spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:software.getsai.06}

# Hibernate JPA (update actualiza las tablas sin borrar los datos)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Para permitir subir imágenes de hasta 10MB
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB